# Generated by Django 6.1 on 2026-09-02 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0003_chaivariety_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chaivariety',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
