# Generated by Django 6.1 on 2026-09-03 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0005_chaicertificate_chaireview_store'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='chai_varieties',
            new_name='chai_varities',
        ),
    ]
